// <auto-generated />
using System;
using Kwiz.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kwiz_backend.Data.Migrations
{
    [DbContext(typeof(KwizDbContext))]
    [Migration("20230910134641_Seed_Technologies")]
    partial class Seed_Technologies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kwiz.Api.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmissionSelectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubmissionSelectionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClosingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OpeningDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinishedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.SubmissionSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeSpentOnQuestion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionSelections");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.TechInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string[]>("Interests")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("TechInterests");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a61b823e-5663-42a5-936c-aea459564c3b"),
                            Description = "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.",
                            Name = "Django",
                            Tags = new[] { "Python", "Web", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("389c99c5-7714-468d-9796-d6bc816b82e4"),
                            Description = "Ruby on Rails is a web application framework written in Ruby that follows the Model-View-Controller (MVC) architectural pattern.",
                            Name = "Ruby on Rails",
                            Tags = new[] { "Ruby", "Web", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("d8f36aff-6678-40e5-ac3f-40c3a6ae283d"),
                            Description = "Angular is a platform and framework for building client-side applications using TypeScript and the Model-View-Controller (MVC) pattern.",
                            Name = "Angular",
                            Tags = new[] { "TypeScript", "Web", "Frontend", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("4f560415-c2a9-4c16-a021-b547c28e416b"),
                            Description = "React is a JavaScript library for building user interfaces, particularly single-page applications.",
                            Name = "React",
                            Tags = new[] { "JavaScript", "Web", "Frontend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("a36c3a13-84d1-456e-a1e5-28e13e7dba05"),
                            Description = "Vue.js is a progressive JavaScript framework for building user interfaces, designed to be incrementally adoptable.",
                            Name = "Vue.js",
                            Tags = new[] { "JavaScript", "Web", "Frontend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("434e2e82-3669-4f50-bbe7-fbc9fe644caf"),
                            Description = "Spring is a Java framework that provides comprehensive infrastructure support for building Java applications.",
                            Name = "Spring",
                            Tags = new[] { "Java", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("b9fe4e04-72f5-4638-a293-869f0eaaad18"),
                            Description = ".NET Core is an open-source, cross-platform framework for building modern, cloud-based, and internet-connected applications.",
                            Name = ".NET Core",
                            Tags = new[] { ".NET", "C#", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("8b6b4413-d674-4af2-9e38-e67e4c0324a3"),
                            Description = "Express.js is a fast, unopinionated, minimalist web framework for Node.js, designed for building web applications and APIs.",
                            Name = "Express.js",
                            Tags = new[] { "JavaScript", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("f9830aec-653c-4bd1-83a6-d1815e1dac82"),
                            Description = "Flask is a lightweight Python web framework that's easy to use and designed to make getting started quick and easy.",
                            Name = "Flask",
                            Tags = new[] { "Python", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("4c2ad544-8336-47e4-82a8-80d36e8cbaa7"),
                            Description = "Laravel is a PHP web application framework known for its elegant syntax and features like routing, authentication, and caching.",
                            Name = "Laravel",
                            Tags = new[] { "PHP", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("0faca12c-9fb7-4522-be57-4b5c8262a434"),
                            Description = "Symfony is a set of reusable PHP components and a web application framework that follows the Model-View-Controller (MVC) pattern.",
                            Name = "Symfony",
                            Tags = new[] { "PHP", "Web", "Backend", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("97d7254e-ffc3-4f0b-931d-5c2a71b77e3d"),
                            Description = "ASP.NET is a web framework developed by Microsoft for building dynamic web applications, web services, and websites.",
                            Name = "ASP.NET",
                            Tags = new[] { "C#", ".NET", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("5fc7e80c-b54d-49f7-92ee-afd863e8ea49"),
                            Description = "Ember.js is a JavaScript framework for building ambitious web applications that handles the boilerplate and provides conventions.",
                            Name = "Ember.js",
                            Tags = new[] { "JavaScript", "Web", "Frontend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("01db026e-c96b-48b8-aac3-4c98df477435"),
                            Description = "Qt is a C++ framework for developing cross-platform applications, including user interfaces and device-specific features.",
                            Name = "Qt",
                            Tags = new[] { "C++", "Desktop" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("c95f9540-c170-4c53-829b-9c38b261528f"),
                            Description = "TensorFlow is an open-source machine learning framework developed by Google for building and training neural network models.",
                            Name = "TensorFlow",
                            Tags = new[] { "Python", "Machine Learning", "AI" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("0ccc4600-a3ed-4660-887c-669207bd1a66"),
                            Description = "PyTorch is an open-source machine learning framework that provides a flexible, dynamic approach to building and training models.",
                            Name = "PyTorch",
                            Tags = new[] { "Python", "Machine Learning", "AI" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("356ea8c4-c50c-479a-9c16-9c06e4dbfcd8"),
                            Description = "Ionic is a popular open-source framework for building cross-platform mobile applications using web technologies like HTML, CSS, and JavaScript.",
                            Name = "Ionic",
                            Tags = new[] { "JavaScript", "Mobile" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("5c8566bc-c29d-4001-a190-abb02006e369"),
                            Description = "RubyMotion is a framework for building native applications on iOS, Android, macOS, and more using the Ruby programming language.",
                            Name = "RubyMotion",
                            Tags = new[] { "Ruby", "Mobile" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("bf972265-1f03-416b-9f19-3a5163573063"),
                            Description = "Meteor is a full-stack JavaScript framework for building real-time web applications, including both the front-end and back-end.",
                            Name = "Meteor",
                            Tags = new[] { "JavaScript", "Web", "Full-Stack" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("28c4f563-2efe-4f34-8df9-c1baeac32992"),
                            Description = "Django REST framework is a powerful toolkit for building Web APIs in Django applications.",
                            Name = "Django REST framework",
                            Tags = new[] { "Python", "Web", "API" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("0d58aab8-907b-4037-9e5e-207177c2b190"),
                            Description = "NestJS is a TypeScript-based Node.js framework for building efficient and scalable server-side applications.",
                            Name = "NestJS",
                            Tags = new[] { "TypeScript", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("129735b5-bfb6-438a-befb-3e5df56aa98f"),
                            Description = "Ruby Grape is a micro-framework for creating REST-like APIs in Ruby.",
                            Name = "Ruby Grape",
                            Tags = new[] { "Ruby", "Web", "API" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("e6bccde8-d5ce-42bc-be0f-2b4580a34400"),
                            Description = "ASP.NET Core is the cross-platform version of ASP.NET, suitable for building modern web applications and APIs.",
                            Name = "ASP.NET Core",
                            Tags = new[] { "C#", ".NET", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("2a0c7573-f7ae-4ef5-a923-71ac5fa548b6"),
                            Description = "Koa is a modern web framework for Node.js that aims to be smaller, more expressive, and more robust.",
                            Name = "Koa",
                            Tags = new[] { "JavaScript", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("277baf27-7856-4f57-a86c-b0f4e1519017"),
                            Description = "Slim is a PHP micro framework that's ideal for building simple, yet powerful web applications and APIs.",
                            Name = "Slim",
                            Tags = new[] { "PHP", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("a4ec1179-c366-492c-aa28-1c1271eee35d"),
                            Description = "Feathers is a web framework for building real-time applications using JavaScript or TypeScript across various platforms.",
                            Name = "Feathers",
                            Tags = new[] { "JavaScript", "Web", "Real-Time" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("f1dbf65b-ce4d-4161-bedd-656268546e8a"),
                            Description = "Sails.js is a full-featured MVC framework for building web applications and APIs using Node.js.",
                            Name = "Sails.js",
                            Tags = new[] { "JavaScript", "Web", "Full-Stack", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("23249c74-81c9-47e9-9084-52367ba81319"),
                            Description = "Phoenix is a web framework for building real-time, fault-tolerant, and distributed systems using Elixir.",
                            Name = "Phoenix",
                            Tags = new[] { "Elixir", "Web", "Real-Time" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("42ca9979-6a09-4ff1-9f22-c679e7718d80"),
                            Description = "Nuxt.js is a higher-level framework built on top of Vue.js, designed for creating universal and single page applications.",
                            Name = "Nuxt.js",
                            Tags = new[] { "Vue.js", "JavaScript", "Web", "Frontend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("baaddf2f-bdd8-460e-b581-3ae086b4a92a"),
                            Description = "Quasar Framework is a high-performance, responsive design framework for building websites, mobile apps, and Electron apps using Vue.js.",
                            Name = "Quasar Framework",
                            Tags = new[] { "Vue.js", "JavaScript", "Web", "Mobile" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("6383cbb8-11ef-415b-accd-b0c97d6da9be"),
                            Description = "Python is an interpreted, high-level and general-purpose programming language.",
                            Name = "Python",
                            Tags = new[] { "Python", "General Purpose", "Interpreted" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("997e36ff-0c39-45c6-b0d7-844dbe61b4f1"),
                            Description = "Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible.",
                            Name = "Java",
                            Tags = new[] { "Java", "General Purpose", "Object-Oriented" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("a9efcc1f-1969-46d7-abbe-c1569fef6e6c"),
                            Description = "C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, with a static type system.",
                            Name = "C",
                            Tags = new[] { "C", "Procedural", "Low-Level" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("802ee8d3-3039-46c1-ac6a-45db7a20e98c"),
                            Description = "C++ is a general-purpose programming language created as an extension of the C programming language, providing object-oriented and generic programming features.",
                            Name = "C++",
                            Tags = new[] { "C++", "Object-Oriented", "Systems" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("e2ad8d3b-624b-45dc-9b24-228c0a96a982"),
                            Description = "C# is a general-purpose, multi-paradigm programming language encompassing strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented, and component-oriented programming disciplines.",
                            Name = "C#",
                            Tags = new[] { "C#", "General Purpose", "Object-Oriented" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("756df21d-ef11-49ab-b0ce-791905e52dfe"),
                            Description = "JavaScript is a high-level, interpreted scripting language used to create dynamic and interactive websites.",
                            Name = "JavaScript",
                            Tags = new[] { "JavaScript", "Web", "Scripting" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("011d6a83-36f1-4ebc-843f-49509a883fe6"),
                            Description = "Ruby is a dynamic, interpreted, reflective, object-oriented, general-purpose programming language.",
                            Name = "Ruby",
                            Tags = new[] { "Ruby", "General Purpose", "Dynamic" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("462bd4a5-e94b-42b7-b9b7-e8396061ec7a"),
                            Description = "Swift is a general-purpose, multi-paradigm programming language developed by Apple Inc. for iOS, iPadOS, macOS, watchOS, tvOS, and Linux.",
                            Name = "Swift",
                            Tags = new[] { "Swift", "Multi-Paradigm", "iOS" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("c532d499-1ee5-45a4-97a7-993f150edbcb"),
                            Description = "Kotlin is a statically typed programming language that runs on the Java Virtual Machine and also can be compiled to JavaScript source code or uses the LLVM compiler infrastructure.",
                            Name = "Kotlin",
                            Tags = new[] { "Kotlin", "Static Typing", "JVM" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("9615dc85-c0be-4c2f-a4b4-ffe5b222298f"),
                            Description = "PHP is a server-side scripting language designed for web development but also used as a general-purpose programming language.",
                            Name = "PHP",
                            Tags = new[] { "PHP", "Web", "Scripting" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("8ff74648-d898-4c4a-a76e-c910368cfc77"),
                            Description = "Go (also known as Golang) is an open-source programming language created by Google. It is statically typed, compiled, and focuses on simplicity and efficiency.",
                            Name = "Go",
                            Tags = new[] { "Go", "Static Typing", "Efficiency" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("b2d3f3db-aad8-41c9-94bd-4ae8775ebfdd"),
                            Description = "Rust is a systems programming language that aims to provide the speed of C and C++ while also focusing on memory safety and thread safety.",
                            Name = "Rust",
                            Tags = new[] { "Rust", "Systems", "Memory Safety" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("47741c56-6b1a-44fd-bdd4-ddb7e3d7f724"),
                            Description = "Perl is a high-level, general-purpose, interpreted, dynamic programming language.",
                            Name = "Perl",
                            Tags = new[] { "Perl", "General Purpose", "Scripting" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("13239d1b-4690-4b8f-b63f-113bdd1488d2"),
                            Description = "Haskell is a functional programming language that emphasizes a concise, declarative coding style.",
                            Name = "Haskell",
                            Tags = new[] { "Haskell", "Functional", "Concise" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("b2410fdd-8e5b-4cef-ab61-07ae930b1962"),
                            Description = "Scala is a general-purpose programming language that integrates functional and object-oriented programming.",
                            Name = "Scala",
                            Tags = new[] { "Scala", "General Purpose", "Functional" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("7b686076-f7dd-4f69-97c2-d2149605e0ea"),
                            Description = "R is a programming language and free software environment used for statistical computing and graphics.",
                            Name = "R",
                            Tags = new[] { "R", "Statistical Computing", "Data Analysis" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("222aa98d-29f3-4552-bc42-e765c6000eb2"),
                            Description = "Lua is a lightweight, high-level, multi-paradigm programming language designed primarily for embedded systems and games.",
                            Name = "Lua",
                            Tags = new[] { "Lua", "Embedded Systems", "Scripting" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("bf0ceb2a-4173-4679-8248-eb5caa521930"),
                            Description = "TypeScript is a strict syntactical superset of JavaScript that adds optional static typing, interfaces, and other advanced features.",
                            Name = "TypeScript",
                            Tags = new[] { "TypeScript", "JavaScript", "Static Typing" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("a286a4a7-3332-4741-81a3-8e3fe81c4d40"),
                            Description = "Julia is a high-level, high-performance programming language for technical computing, with syntax that is familiar to users of other technical computing environments.",
                            Name = "Julia",
                            Tags = new[] { "Julia", "Technical Computing", "Performance" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("f2ecade4-4a25-419d-91b9-9cff1ce31853"),
                            Description = "Dart is a programming language designed for building web, server, and mobile applications.",
                            Name = "Dart",
                            Tags = new[] { "Dart", "Web", "Mobile" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("b65bcebb-ec23-4c33-962f-ba6b6bb4632e"),
                            Description = "COBOL is a compiled English-like computer programming language designed for business use.",
                            Name = "Cobol",
                            Tags = new[] { "COBOL", "Business", "Compiled" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("9bca5879-015b-4d68-a0e5-4308d6c084e3"),
                            Description = "Erlang is a general-purpose, concurrent, functional programming language used primarily in telecommunications and other high-availability systems.",
                            Name = "Erlang",
                            Tags = new[] { "Erlang", "Concurrent", "Functional" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("481932a6-504b-4ba0-a14c-606833072299"),
                            Description = "Groovy is a dynamic programming language that runs on the Java Virtual Machine and can be used as both a programming language and a scripting language.",
                            Name = "Groovy",
                            Tags = new[] { "Groovy", "Dynamic", "JVM" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("cc4117fd-7818-44d7-99a5-6c53c154d4f8"),
                            Description = "Haxe is a high-level, open-source programming language that can be compiled to various target languages, including JavaScript, C++, and more.",
                            Name = "Haxe",
                            Tags = new[] { "Haxe", "High-Level", "Cross-Compilation" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("305e9c09-2c90-4bad-ab6b-ae7570ad684b"),
                            Description = "Io is a small, prototype-based programming language inspired by Smalltalk, Lisp, and other languages.",
                            Name = "Io",
                            Tags = new[] { "Io", "Prototype-Based", "Small" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("5b2dd237-e0ea-442e-b200-4feec9a91a77"),
                            Description = "J is a high-level, interpreted programming language, primarily used for mathematical and statistical analysis.",
                            Name = "J",
                            Tags = new[] { "J", "Mathematical", "Interpreted" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("4eee617c-7f4e-46a0-b783-b1b8073d346c"),
                            Description = "Maxima is a computer algebra system based on a 1982 version of Macsyma.",
                            Name = "Maxima",
                            Tags = new[] { "Maxima", "Algebra", "Mathematics" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("c18854f0-6152-42f0-8de8-73878c29c89c"),
                            Description = "ML is a general-purpose functional programming language developed by Robin Milner and others in the early 1970s.",
                            Name = "ML",
                            Tags = new[] { "ML", "Functional", "General Purpose" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("541e9968-d017-4bf6-a41a-22b667cff92e"),
                            Description = "Nim is a statically typed, imperative programming language that focuses on performance, portability, and expressiveness.",
                            Name = "Nim",
                            Tags = new[] { "Nim", "Statically Typed", "Performance" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("5adf86fc-dbe1-4b0c-8a05-45b4f14a3238"),
                            Description = "Objective-C is a general-purpose, object-oriented programming language used by Apple for the macOS and iOS operating systems.",
                            Name = "Objective-C",
                            Tags = new[] { "Objective-C", "Object-Oriented", "Apple" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("0e68b026-96c3-487c-8c61-c1466042dd97"),
                            Description = "OCaml is a general-purpose, functional, and imperative programming language.",
                            Name = "OCaml",
                            Tags = new[] { "OCaml", "Functional", "General Purpose" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("c372b7c2-4e09-4877-a6d2-8ae995e8df11"),
                            Description = "Pascal is an influential imperative and procedural programming language, designed in the late 1960s as a small and efficient language intended to encourage good programming practices.",
                            Name = "Pascal",
                            Tags = new[] { "Pascal", "Imperative", "Efficient" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("78ea6a5a-4708-4904-bf20-53526e9d62da"),
                            Description = "PL/I is a procedural, imperative computer programming language designed for scientific, engineering, business, and systems programming applications.",
                            Name = "PL/I",
                            Tags = new[] { "PL/I", "Procedural", "Scientific" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("22d11d39-7410-4d12-86e1-619e42248dd9"),
                            Description = "PostScript is a page description language and programming language used primarily in the electronic and desktop publishing areas.",
                            Name = "PostScript",
                            Tags = new[] { "PostScript", "Page Description", "Publishing" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("66046545-0747-4369-a71c-2e284914edbb"),
                            Description = "PowerShell is a task automation and configuration management framework from Microsoft, consisting of a command-line shell and associated scripting language.",
                            Name = "PowerShell",
                            Tags = new[] { "PowerShell", "Automation", "Microsoft" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("10024547-e79d-45e5-a272-24b495cbe1e6"),
                            Description = "PureScript is a strongly-typed functional programming language that compiles to JavaScript.",
                            Name = "PureScript",
                            Tags = new[] { "PureScript", "Functional", "TypeScript" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("91351a43-7b88-463c-b4d8-fcb33221ae25"),
                            Description = "REXX is an interpreted language that is used primarily for text processing.",
                            Name = "REXX",
                            Tags = new[] { "REXX", "Interpreted", "Text Processing" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("f94e3f88-b182-4c23-b821-45443ef706b0"),
                            Description = "Ring is a dynamic and general-purpose programming language that is designed to be simple and easy to learn.",
                            Name = "Ring",
                            Tags = new[] { "Ring", "General Purpose", "Dynamic" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("8664d04c-390f-4c10-bbd8-60867036d06c"),
                            Description = "SAS is a software suite used for advanced analytics, business intelligence, and data management.",
                            Name = "SAS",
                            Tags = new[] { "SAS", "Analytics", "Data Management" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("2330e078-a8d7-444f-9647-bffb419f42e3"),
                            Description = "Scratch is a visual programming language and online community where users can create their own interactive stories, games, and animations.",
                            Name = "Scratch",
                            Tags = new[] { "Scratch", "Visual", "Education" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("f1011667-d18b-44c8-90e2-18e5d85e1be1"),
                            Description = "Tcl is a high-level, dynamic programming language often used for rapid prototyping and scripting.",
                            Name = "Tcl",
                            Tags = new[] { "Tcl", "Scripting", "Dynamic" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("38b07b1f-b7f5-477b-9fd7-893814d03a4c"),
                            Description = "Turing is a Pascal-like programming language developed for teaching programming concepts to beginners.",
                            Name = "Turing",
                            Tags = new[] { "Turing", "Education", "Teaching" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("060e77b5-e1ef-499f-8124-08a010f6c1f4"),
                            Description = "Vim script is a scripting language used for customizing and extending the Vim text editor.",
                            Name = "Vim script",
                            Tags = new[] { "Vim", "Scripting", "Text Editor" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("f520ae50-b179-4a66-b3b2-f237ed0971f5"),
                            Description = "Visual Basic is a third-generation event-driven programming language from Microsoft.",
                            Name = "Visual Basic",
                            Tags = new[] { "Visual Basic", "Microsoft", "Event-Driven" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("8acea1d6-7821-4d68-ad0f-50b342a2b877"),
                            Description = "X10 is a high-level programming language that is designed for high-performance, high-productivity computing.",
                            Name = "X10",
                            Tags = new[] { "X10", "High-Performance", "Concurrent" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("52b7f637-109a-491d-971e-7201f7e2bdb0"),
                            Description = "Zig is a general-purpose programming language designed for robustness, optimality, and maintainability.",
                            Name = "Zig",
                            Tags = new[] { "Zig", "General Purpose", "Robust" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("365091b8-7e20-4527-8e2d-5363692c8c7f"),
                            Description = "Visual Studio Code is a free source-code editor made by Microsoft for Windows, Linux, and macOS.",
                            Name = "Visual Studio Code",
                            Tags = new[] { "IDE", "Editor", "Microsoft" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("8b3c3780-4b87-4305-90cd-fd6e4e473a27"),
                            Description = "IntelliJ IDEA is a powerful Java integrated development environment (IDE) for developing computer software.",
                            Name = "IntelliJ IDEA",
                            Tags = new[] { "IDE", "Java", "JetBrains" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("08b4d4fa-b50e-416d-a21a-9811b9cd3933"),
                            Description = "Eclipse is an integrated development environment (IDE) used in computer programming.",
                            Name = "Eclipse",
                            Tags = new[] { "IDE", "Java", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("b408faa6-85b8-42e9-8347-bef81c7ff5ee"),
                            Description = "PyCharm is an integrated development environment (IDE) used in computer programming for Python language.",
                            Name = "PyCharm",
                            Tags = new[] { "IDE", "Python", "JetBrains" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("13da0360-ff19-4c98-96e8-9b7b6d942640"),
                            Description = "Sublime Text is a proprietary cross-platform source code editor with a Python application programming interface (API).",
                            Name = "Sublime Text",
                            Tags = new[] { "Editor", "Text Editor", "Proprietary" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("1e5c807f-08d4-464c-9057-f8819748848a"),
                            Description = "Atom is a free and open-source text and source code editor for macOS, Linux, and Microsoft Windows.",
                            Name = "Atom",
                            Tags = new[] { "Editor", "Text Editor", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("e8e6db43-6d3c-469a-9033-9acd7e42147e"),
                            Description = "Visual Studio is an integrated development environment (IDE) developed by Microsoft.",
                            Name = "Visual Studio",
                            Tags = new[] { "IDE", "Microsoft", "Windows" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("c15db080-fedc-456c-91eb-791e92bddd52"),
                            Description = "NetBeans is an integrated development environment (IDE) for Java. It supports development of all Java application types.",
                            Name = "NetBeans",
                            Tags = new[] { "IDE", "Java", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("26dcd089-f586-45a4-808f-711896d84723"),
                            Description = "Xcode is an integrated development environment (IDE) for macOS containing a suite of software development tools.",
                            Name = "Xcode",
                            Tags = new[] { "IDE", "Apple", "macOS" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("15d5f9f9-9e19-417f-9822-f79b65d80217"),
                            Description = "Android Studio is the official integrated development environment (IDE) for Android application development.",
                            Name = "Android Studio",
                            Tags = new[] { "IDE", "Android", "Google" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("199883e4-d552-4fb2-8f87-fe239311eb43"),
                            Description = "Git is a distributed version control system for tracking changes in source code during software development.",
                            Name = "Git",
                            Tags = new[] { "Version Control", "Git", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("82afe9a3-a537-443b-97c2-0eda2f8a6343"),
                            Description = "GitHub is a web-based platform for version control and collaboration using Git.",
                            Name = "GitHub",
                            Tags = new[] { "Version Control", "Collaboration", "Web" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("b4d4a790-79fc-42e2-8fc3-cbc886432802"),
                            Description = "Jupyter Notebook is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations, and narrative text.",
                            Name = "Jupyter Notebook",
                            Tags = new[] { "Notebook", "Python", "Data Science" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("fb60d668-e9fb-4883-9c91-0028bddc066d"),
                            Description = "Docker is a set of platform as a service (PaaS) products that use OS-level virtualization to deliver software in packages called containers.",
                            Name = "Docker",
                            Tags = new[] { "Containerization", "Virtualization", "DevOps" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("aabf86ff-a4fb-4c86-8074-e7e313afb3c4"),
                            Description = "Postman is a collaboration platform for API development that simplifies the process of developing APIs that allow software to communicate.",
                            Name = "Postman",
                            Tags = new[] { "API Development", "Testing", "Collaboration" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("ff991007-6d77-4166-9241-47b8f41e4954"),
                            Description = "Webpack is an open-source JavaScript module bundler. It takes modules with dependencies and generates static assets representing those modules.",
                            Name = "Webpack",
                            Tags = new[] { "Module Bundler", "JavaScript", "Build Tool" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("b82c7046-9efb-42be-8892-39d011b53e26"),
                            Description = "npm is a package manager for the JavaScript programming language.",
                            Name = "npm",
                            Tags = new[] { "Package Manager", "JavaScript", "Node.js" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("6d48a7d5-cc70-48df-8d4e-acae03ad2b62"),
                            Description = "Selenium is a portable framework for testing web applications. Selenium provides a playback tool for authoring functional tests.",
                            Name = "Selenium",
                            Tags = new[] { "Testing", "Web", "Automated Testing" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("20735ad2-7dff-472b-91ff-659d99fb5b5e"),
                            Description = "Visual Studio Online is a web-based integrated development environment (IDE) for software developers.",
                            Name = "Visual Studio Online",
                            Tags = new[] { "IDE", "Microsoft", "Web" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("e1d394bb-b450-47de-a788-4f99bc55fa9f"),
                            Description = "CMake is an open-source, cross-platform family of tools designed to build, test, and package software.",
                            Name = "CMake",
                            Tags = new[] { "Build Tool", "Cross-Platform", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("139cef88-4096-4053-b523-910b0341bad7"),
                            Description = "JIRA is a proprietary issue tracking product developed by Atlassian that allows bug tracking and agile project management.",
                            Name = "JIRA",
                            Tags = new[] { "Project Management", "Issue Tracking", "Atlassian" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("195392c3-7cf6-413e-b39c-4be18eaa2bac"),
                            Description = "Confluence is a web-based corporate wiki application developed by Atlassian.",
                            Name = "Confluence",
                            Tags = new[] { "Collaboration", "Wiki", "Atlassian" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("9adfe3e8-6c62-4a91-9574-4dd8b0c31a85"),
                            Description = "Slack is a proprietary business communication platform that offers many IRC-style features.",
                            Name = "Slack",
                            Tags = new[] { "Communication", "Collaboration", "Messaging" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("9c4acd31-81ca-448e-a43e-69bc86043b5a"),
                            Description = "Trello is a web-based list-making application originally made by Fog Creek Software in 2011, that was spun out to form the basis of a separate company in 2014.",
                            Name = "Trello",
                            Tags = new[] { "Project Management", "Agile", "Productivity" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("1fe00da7-4683-4e59-b231-42be49f5fe59"),
                            Description = "Vagrant is an open-source software product for building and maintaining portable virtual software development environments.",
                            Name = "Vagrant",
                            Tags = new[] { "Virtualization", "Development Environment", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("ff32ab4a-be7c-4c53-959f-9e40ecb019f0"),
                            Description = "Ansible is an open-source automation tool that automates software provisioning, configuration management, and application deployment.",
                            Name = "Ansible",
                            Tags = new[] { "Automation", "Configuration Management", "DevOps" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("4a1ee378-e616-49ca-b884-cbc23a3344b0"),
                            Description = "Version control is a system that records changes to a file or set of files over time, so that you can recall specific versions later.",
                            Name = "Version Control",
                            Tags = new[] { "Version Control", "Collaboration", "History" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("d3f9d2c7-a635-4f6b-a57c-da844171fa64"),
                            Description = "Agile is an iterative approach to software development that emphasizes flexibility, collaboration, and customer feedback.",
                            Name = "Agile",
                            Tags = new[] { "Agile", "Methodology", "Iterations" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("497a7757-66fe-46ec-89ba-9eb2895b9768"),
                            Description = "DevOps is a set of practices that combines software development (Dev) and IT operations (Ops) to shorten the software development life cycle and improve deployment frequency.",
                            Name = "DevOps",
                            Tags = new[] { "DevOps", "Collaboration", "Automation" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("bc732dad-8593-4652-82c2-5174efa777f8"),
                            Description = "An algorithm is a step-by-step procedure or formula for solving a problem or accomplishing a task.",
                            Name = "Algorithm",
                            Tags = new[] { "Algorithm", "Problem Solving", "Procedure" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("1131129a-60e4-4cc8-9441-136ac78006da"),
                            Description = "A data structure is a way of organizing and storing data in a computer so that it can be used efficiently.",
                            Name = "Data Structure",
                            Tags = new[] { "Data Structure", "Organization", "Efficiency" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("91c990ae-4192-4cdd-991d-9e22c90a764b"),
                            Description = "An API (Application Programming Interface) is a set of rules and protocols that allows different software applications to communicate with each other.",
                            Name = "API",
                            Tags = new[] { "API", "Communication", "Integration" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("5669fe67-b55e-4f32-b63e-8d21e528f0fa"),
                            Description = "A database is an organized collection of structured information, or data, typically stored electronically in a computer system.",
                            Name = "Database",
                            Tags = new[] { "Database", "Data Storage", "Structured" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("f7fefa93-c53e-4997-a2bb-2f40ba032a43"),
                            Description = "Cloud computing is the delivery of computing services—servers, storage, databases, networking, software, over the Cloud (Internet).",
                            Name = "Cloud Computing",
                            Tags = new[] { "Cloud Computing", "Services", "Internet" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("2156463e-432a-4937-887c-d0d9a9e641e0"),
                            Description = "Machine learning is a subset of artificial intelligence that involves training computers to learn from data and improve their performance over time.",
                            Name = "Machine Learning",
                            Tags = new[] { "Machine Learning", "Artificial Intelligence", "Data" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("c7d5d113-3c84-4386-bc56-ea8677cb372a"),
                            Description = "Artificial intelligence (AI) is the simulation of human intelligence in machines that are capable of performing tasks that typically require human intelligence.",
                            Name = "Artificial Intelligence",
                            Tags = new[] { "Artificial Intelligence", "Simulation", "Automation" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("6a41a0b6-723b-4939-96c6-f2324d7310ef"),
                            Description = "Big data refers to extremely large datasets that may be analyzed computationally to reveal patterns, trends, and associations.",
                            Name = "Big Data",
                            Tags = new[] { "Big Data", "Data Analysis", "Patterns" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("a2537e9e-4afc-4ec8-8b01-f79373e85810"),
                            Description = "Cybersecurity is the practice of protecting computer systems, networks, and data from theft, damage, or unauthorized access.",
                            Name = "Cybersecurity",
                            Tags = new[] { "Cybersecurity", "Protection", "Networks" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("366483ca-2b61-4bb3-9f09-7e94f20e9a83"),
                            Description = "Code review is a systematic examination of computer source code. It is intended to find mistakes overlooked in initial development.",
                            Name = "Code Review",
                            Tags = new[] { "Code Review", "Quality Assurance", "Collaboration" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("e214d688-12ab-42be-9448-235edb15caf5"),
                            Description = "Code refactoring is the process of restructuring existing computer code without changing its external behavior.",
                            Name = "Code Refactoring",
                            Tags = new[] { "Code Refactoring", "Code Improvement", "Restructuring" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("6cecbbc6-f43d-466d-9650-b8d7161cf225"),
                            Description = "Continuous Integration (CI) is a software development practice where code changes are automatically built, tested, and integrated into the shared repository.",
                            Name = "Continuous Integration",
                            Tags = new[] { "Continuous Integration", "Automation", "Testing" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("41c51976-8884-488c-a36e-3d799b50832e"),
                            Description = "Continuous Deployment is a software development practice where every code change that passes automated testing is automatically deployed to production.",
                            Name = "Continuous Deployment",
                            Tags = new[] { "Continuous Deployment", "Automation", "Production" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("ce7b2acf-ae00-49c5-b40f-f9fb3942f14f"),
                            Description = "Code quality refers to the overall robustness, maintainability, readability, and performance of a software codebase.",
                            Name = "Code Quality",
                            Tags = new[] { "Code Quality", "Robustness", "Maintainability" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("96dfec93-9b99-43d1-947f-baf7b1221647"),
                            Description = "Unit testing is a software testing method where individual units or components of a software are tested in isolation.",
                            Name = "Unit Testing",
                            Tags = new[] { "Unit Testing", "Testing", "Components" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("ddba0465-b9a8-408d-b289-f8c95752639b"),
                            Description = "Continuous monitoring involves the regular collection and analysis of data to evaluate the performance and security of a system.",
                            Name = "Continuous Monitoring",
                            Tags = new[] { "Continuous Monitoring", "Performance", "Security" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("b3d02b02-853a-4c8c-84ff-8d330d4d6de9"),
                            Description = "Responsive design is an approach to web design that makes web pages render well on a variety of devices and window or screen sizes.",
                            Name = "Responsive Design",
                            Tags = new[] { "Responsive Design", "Web", "User Experience" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("7225b812-857f-4017-9282-95dba1d5affd"),
                            Description = "User Experience (UX) refers to a person's emotions and attitudes about using a particular product, system, or service.",
                            Name = "User Experience (UX)",
                            Tags = new[] { "User Experience", "Design", "Emotions" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("e5cf94d8-6417-459c-8a54-e30ca386fdb6"),
                            Description = "User Interface (UI) encompasses the visual elements, controls, and layouts through which a user interacts with a software or hardware.",
                            Name = "User Interface (UI)",
                            Tags = new[] { "User Interface", "Design", "Interactions" },
                            Type = "Concept"
                        });
                });

            modelBuilder.Entity("QuizQuizQuestion", b =>
                {
                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizzesId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionsId", "QuizzesId");

                    b.HasIndex("QuizzesId");

                    b.ToTable("QuizQuizQuestion", (string)null);
                });

            modelBuilder.Entity("Kwiz.Api.Entities.QuestionOption", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.QuizQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwiz.Api.Entities.SubmissionSelection", "SubmissionSelection")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("SubmissionSelectionId");

                    b.Navigation("Question");

                    b.Navigation("SubmissionSelection");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Submission", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.Quiz", "Quiz")
                        .WithMany("Submissions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.SubmissionSelection", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.QuizQuestion", "Question")
                        .WithMany("SubmissionSelections")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwiz.Api.Entities.Submission", null)
                        .WithMany("Selections")
                        .HasForeignKey("SubmissionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizQuizQuestion", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.QuizQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwiz.Api.Entities.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizzesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Quiz", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.QuizQuestion", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("SubmissionSelections");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Submission", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.SubmissionSelection", b =>
                {
                    b.Navigation("SelectedOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
