// <auto-generated />
using System;
using Kwiz.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace kwiz_backend.Data.Migrations
{
    [DbContext(typeof(KwizDbContext))]
    [Migration("20230910151644_UserIntereset_Technology_Relationship")]
    partial class UserIntereset_Technology_Relationship
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Kwiz.Api.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmissionSelectionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubmissionSelectionId");

                    b.ToTable("QuestionOptions");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ClosingDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OpeningDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.QuizQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]");

                    b.Property<int>("TimeLimitSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("QuizQuestions");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Submission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinishedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("Submissions");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.SubmissionSelection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSkipped")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SubmissionId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeSpentOnQuestion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SubmissionId");

                    b.ToTable("SubmissionSelections");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.TechInterest", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("UserId");

                    b.ToTable("TechInterests");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Technology", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasAnnotation("Relational:JsonPropertyName", "name");

                    b.Property<string[]>("Tags")
                        .HasColumnType("text[]")
                        .HasAnnotation("Relational:JsonPropertyName", "tags");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasAnnotation("Relational:JsonPropertyName", "type");

                    b.HasKey("Id");

                    b.ToTable("Technologies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab55e4f8-1cd5-4257-94b4-195d87abdfbe"),
                            Description = "Django is a high-level Python web framework that encourages rapid development and clean, pragmatic design.",
                            Name = "Django",
                            Tags = new[] { "Python", "Web", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("0306e67d-31dc-4a64-92f7-ab3db08df992"),
                            Description = "Ruby on Rails is a web application framework written in Ruby that follows the Model-View-Controller (MVC) architectural pattern.",
                            Name = "Ruby on Rails",
                            Tags = new[] { "Ruby", "Web", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("0db18422-4742-42df-b080-9dde536e38b6"),
                            Description = "Angular is a platform and framework for building client-side applications using TypeScript and the Model-View-Controller (MVC) pattern.",
                            Name = "Angular",
                            Tags = new[] { "TypeScript", "Web", "Frontend", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("89a67848-8315-46d7-9e95-54a830a0a9ca"),
                            Description = "React is a JavaScript library for building user interfaces, particularly single-page applications.",
                            Name = "React",
                            Tags = new[] { "JavaScript", "Web", "Frontend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("cd90708c-ca18-42df-8052-7296cdafe0bb"),
                            Description = "Vue.js is a progressive JavaScript framework for building user interfaces, designed to be incrementally adoptable.",
                            Name = "Vue.js",
                            Tags = new[] { "JavaScript", "Web", "Frontend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("a935fa9a-aff1-4882-a2e4-aa704489d974"),
                            Description = "Spring is a Java framework that provides comprehensive infrastructure support for building Java applications.",
                            Name = "Spring",
                            Tags = new[] { "Java", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("3ec4982e-875b-4bc3-a23b-fd0bfff7803c"),
                            Description = ".NET Core is an open-source, cross-platform framework for building modern, cloud-based, and internet-connected applications.",
                            Name = ".NET Core",
                            Tags = new[] { ".NET", "C#", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("0d51f623-6157-4aa7-959b-7f6c1de28495"),
                            Description = "Express.js is a fast, unopinionated, minimalist web framework for Node.js, designed for building web applications and APIs.",
                            Name = "Express.js",
                            Tags = new[] { "JavaScript", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("f24d6441-b574-40b1-b8e8-0c739cd786fa"),
                            Description = "Flask is a lightweight Python web framework that's easy to use and designed to make getting started quick and easy.",
                            Name = "Flask",
                            Tags = new[] { "Python", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("02fc5071-e4f1-48a7-97d3-84803b8e21ae"),
                            Description = "Laravel is a PHP web application framework known for its elegant syntax and features like routing, authentication, and caching.",
                            Name = "Laravel",
                            Tags = new[] { "PHP", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("4ded309b-9db5-490c-bc26-4ac1f623675d"),
                            Description = "Symfony is a set of reusable PHP components and a web application framework that follows the Model-View-Controller (MVC) pattern.",
                            Name = "Symfony",
                            Tags = new[] { "PHP", "Web", "Backend", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("2f2a9685-e210-4b57-b474-42c8033595cf"),
                            Description = "ASP.NET is a web framework developed by Microsoft for building dynamic web applications, web services, and websites.",
                            Name = "ASP.NET",
                            Tags = new[] { "C#", ".NET", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("9e4a2a4b-b2a5-4a3d-a885-fe1cb7639144"),
                            Description = "Ember.js is a JavaScript framework for building ambitious web applications that handles the boilerplate and provides conventions.",
                            Name = "Ember.js",
                            Tags = new[] { "JavaScript", "Web", "Frontend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("fe205e3c-4569-41d2-a5d9-db35478c3468"),
                            Description = "Qt is a C++ framework for developing cross-platform applications, including user interfaces and device-specific features.",
                            Name = "Qt",
                            Tags = new[] { "C++", "Desktop" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("75e05f77-ccce-4c7e-9637-03645287ce50"),
                            Description = "TensorFlow is an open-source machine learning framework developed by Google for building and training neural network models.",
                            Name = "TensorFlow",
                            Tags = new[] { "Python", "Machine Learning", "AI" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("81ca9fa9-ba3e-4a0b-9c98-891b01e7fbb0"),
                            Description = "PyTorch is an open-source machine learning framework that provides a flexible, dynamic approach to building and training models.",
                            Name = "PyTorch",
                            Tags = new[] { "Python", "Machine Learning", "AI" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("4e41ff37-f64e-4947-a76b-bdc85dfadc5e"),
                            Description = "Ionic is a popular open-source framework for building cross-platform mobile applications using web technologies like HTML, CSS, and JavaScript.",
                            Name = "Ionic",
                            Tags = new[] { "JavaScript", "Mobile" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("bd247a4e-f81b-468f-8ece-f6cabc2281cb"),
                            Description = "RubyMotion is a framework for building native applications on iOS, Android, macOS, and more using the Ruby programming language.",
                            Name = "RubyMotion",
                            Tags = new[] { "Ruby", "Mobile" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("c41c452a-d118-45c8-988b-811a4c1e5a7b"),
                            Description = "Meteor is a full-stack JavaScript framework for building real-time web applications, including both the front-end and back-end.",
                            Name = "Meteor",
                            Tags = new[] { "JavaScript", "Web", "Full-Stack" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("64e06965-4208-4fb6-b1a9-aade88691c6a"),
                            Description = "Django REST framework is a powerful toolkit for building Web APIs in Django applications.",
                            Name = "Django REST framework",
                            Tags = new[] { "Python", "Web", "API" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("47d3785d-fd66-4c1e-bcfc-b268db056603"),
                            Description = "NestJS is a TypeScript-based Node.js framework for building efficient and scalable server-side applications.",
                            Name = "NestJS",
                            Tags = new[] { "TypeScript", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("783a2ca1-cbed-4d17-9451-b40ad89dda5f"),
                            Description = "Ruby Grape is a micro-framework for creating REST-like APIs in Ruby.",
                            Name = "Ruby Grape",
                            Tags = new[] { "Ruby", "Web", "API" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("a1cb3152-8e37-4ebe-b9de-5ab3e8b95ad7"),
                            Description = "ASP.NET Core is the cross-platform version of ASP.NET, suitable for building modern web applications and APIs.",
                            Name = "ASP.NET Core",
                            Tags = new[] { "C#", ".NET", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("5a4f3f80-6e18-4921-b470-4fc31ee88008"),
                            Description = "Koa is a modern web framework for Node.js that aims to be smaller, more expressive, and more robust.",
                            Name = "Koa",
                            Tags = new[] { "JavaScript", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("c10b3c92-2786-450f-b55d-bc0bc042eca2"),
                            Description = "Slim is a PHP micro framework that's ideal for building simple, yet powerful web applications and APIs.",
                            Name = "Slim",
                            Tags = new[] { "PHP", "Web", "Backend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("73072469-b67e-421e-85bf-dfa6cc0177c1"),
                            Description = "Feathers is a web framework for building real-time applications using JavaScript or TypeScript across various platforms.",
                            Name = "Feathers",
                            Tags = new[] { "JavaScript", "Web", "Real-Time" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("b7c2983d-1c56-4848-b486-219b9d75d158"),
                            Description = "Sails.js is a full-featured MVC framework for building web applications and APIs using Node.js.",
                            Name = "Sails.js",
                            Tags = new[] { "JavaScript", "Web", "Full-Stack", "MVC" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("ec82bc6e-584f-44d3-9c62-b6a0fdcfc9ec"),
                            Description = "Phoenix is a web framework for building real-time, fault-tolerant, and distributed systems using Elixir.",
                            Name = "Phoenix",
                            Tags = new[] { "Elixir", "Web", "Real-Time" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("f78803fc-0665-4d8e-8d0b-0e807b042ca7"),
                            Description = "Nuxt.js is a higher-level framework built on top of Vue.js, designed for creating universal and single page applications.",
                            Name = "Nuxt.js",
                            Tags = new[] { "Vue.js", "JavaScript", "Web", "Frontend" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("bbbce099-00fd-4524-ba5e-45ea7778f051"),
                            Description = "Quasar Framework is a high-performance, responsive design framework for building websites, mobile apps, and Electron apps using Vue.js.",
                            Name = "Quasar Framework",
                            Tags = new[] { "Vue.js", "JavaScript", "Web", "Mobile" },
                            Type = "Framework"
                        },
                        new
                        {
                            Id = new Guid("ac1e3f24-aa7c-495a-9854-14432deafc06"),
                            Description = "Python is an interpreted, high-level and general-purpose programming language.",
                            Name = "Python",
                            Tags = new[] { "Python", "General Purpose", "Interpreted" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("8ed8e010-7090-42fe-95f6-b78e0f4fdd7e"),
                            Description = "Java is a general-purpose programming language that is class-based, object-oriented, and designed to have as few implementation dependencies as possible.",
                            Name = "Java",
                            Tags = new[] { "Java", "General Purpose", "Object-Oriented" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("1da952fe-bb4e-4956-85cf-2ab0f0259442"),
                            Description = "C is a general-purpose, procedural computer programming language supporting structured programming, lexical variable scope, and recursion, with a static type system.",
                            Name = "C",
                            Tags = new[] { "C", "Procedural", "Low-Level" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("6b7e68d8-dcbd-40f8-bc97-d4b8128f4d4b"),
                            Description = "C++ is a general-purpose programming language created as an extension of the C programming language, providing object-oriented and generic programming features.",
                            Name = "C++",
                            Tags = new[] { "C++", "Object-Oriented", "Systems" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("e3602e1f-7565-48c9-b0b0-e39a8b2f4676"),
                            Description = "C# is a general-purpose, multi-paradigm programming language encompassing strong typing, lexically scoped, imperative, declarative, functional, generic, object-oriented, and component-oriented programming disciplines.",
                            Name = "C#",
                            Tags = new[] { "C#", "General Purpose", "Object-Oriented" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("14e0dd5b-680f-4069-874b-9c49c5bf2bbb"),
                            Description = "JavaScript is a high-level, interpreted scripting language used to create dynamic and interactive websites.",
                            Name = "JavaScript",
                            Tags = new[] { "JavaScript", "Web", "Scripting" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("41311a77-ca8f-4f1f-890f-06db40f587e2"),
                            Description = "Ruby is a dynamic, interpreted, reflective, object-oriented, general-purpose programming language.",
                            Name = "Ruby",
                            Tags = new[] { "Ruby", "General Purpose", "Dynamic" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("e1711529-2d0b-481a-a2ea-86ed24758e2b"),
                            Description = "Swift is a general-purpose, multi-paradigm programming language developed by Apple Inc. for iOS, iPadOS, macOS, watchOS, tvOS, and Linux.",
                            Name = "Swift",
                            Tags = new[] { "Swift", "Multi-Paradigm", "iOS" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("9ca3b134-43b8-4857-b676-199a9fe172b7"),
                            Description = "Kotlin is a statically typed programming language that runs on the Java Virtual Machine and also can be compiled to JavaScript source code or uses the LLVM compiler infrastructure.",
                            Name = "Kotlin",
                            Tags = new[] { "Kotlin", "Static Typing", "JVM" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("be21b4b9-0b75-4941-af37-7d16753bd5ce"),
                            Description = "PHP is a server-side scripting language designed for web development but also used as a general-purpose programming language.",
                            Name = "PHP",
                            Tags = new[] { "PHP", "Web", "Scripting" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("e8dbd861-1a45-4789-8309-a1cef7edd194"),
                            Description = "Go (also known as Golang) is an open-source programming language created by Google. It is statically typed, compiled, and focuses on simplicity and efficiency.",
                            Name = "Go",
                            Tags = new[] { "Go", "Static Typing", "Efficiency" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("4365a543-2f45-4912-ab25-249e3b5d7151"),
                            Description = "Rust is a systems programming language that aims to provide the speed of C and C++ while also focusing on memory safety and thread safety.",
                            Name = "Rust",
                            Tags = new[] { "Rust", "Systems", "Memory Safety" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("5f8246a0-9f67-469f-9c6b-05b50a013481"),
                            Description = "Perl is a high-level, general-purpose, interpreted, dynamic programming language.",
                            Name = "Perl",
                            Tags = new[] { "Perl", "General Purpose", "Scripting" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("e89b98ae-d38f-4d74-981f-6b2d9fb05371"),
                            Description = "Haskell is a functional programming language that emphasizes a concise, declarative coding style.",
                            Name = "Haskell",
                            Tags = new[] { "Haskell", "Functional", "Concise" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("abc8ac0a-9fd6-4eb7-b606-45e431ee817c"),
                            Description = "Scala is a general-purpose programming language that integrates functional and object-oriented programming.",
                            Name = "Scala",
                            Tags = new[] { "Scala", "General Purpose", "Functional" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("b210e99a-4d21-439d-97ac-b3ca6f33d6f4"),
                            Description = "R is a programming language and free software environment used for statistical computing and graphics.",
                            Name = "R",
                            Tags = new[] { "R", "Statistical Computing", "Data Analysis" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("53e067ec-5b2e-4900-ae62-b7abcfe2a3c8"),
                            Description = "Lua is a lightweight, high-level, multi-paradigm programming language designed primarily for embedded systems and games.",
                            Name = "Lua",
                            Tags = new[] { "Lua", "Embedded Systems", "Scripting" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("ec395511-9f1b-442e-bc1e-271c73590b84"),
                            Description = "TypeScript is a strict syntactical superset of JavaScript that adds optional static typing, interfaces, and other advanced features.",
                            Name = "TypeScript",
                            Tags = new[] { "TypeScript", "JavaScript", "Static Typing" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("41b668bf-386f-44e8-999c-027822de7e99"),
                            Description = "Julia is a high-level, high-performance programming language for technical computing, with syntax that is familiar to users of other technical computing environments.",
                            Name = "Julia",
                            Tags = new[] { "Julia", "Technical Computing", "Performance" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("a281c36b-b93e-41a3-a2b4-50a8af973db2"),
                            Description = "Dart is a programming language designed for building web, server, and mobile applications.",
                            Name = "Dart",
                            Tags = new[] { "Dart", "Web", "Mobile" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("512a9a40-9185-430c-be71-f727dbc17905"),
                            Description = "COBOL is a compiled English-like computer programming language designed for business use.",
                            Name = "Cobol",
                            Tags = new[] { "COBOL", "Business", "Compiled" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("2881d986-1323-4e88-b0e7-6897576f4338"),
                            Description = "Erlang is a general-purpose, concurrent, functional programming language used primarily in telecommunications and other high-availability systems.",
                            Name = "Erlang",
                            Tags = new[] { "Erlang", "Concurrent", "Functional" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("207084d3-d64f-4707-bae8-0fbc5fa7c10b"),
                            Description = "Groovy is a dynamic programming language that runs on the Java Virtual Machine and can be used as both a programming language and a scripting language.",
                            Name = "Groovy",
                            Tags = new[] { "Groovy", "Dynamic", "JVM" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("a77e4958-4179-47e0-a727-bfb02f06906a"),
                            Description = "Haxe is a high-level, open-source programming language that can be compiled to various target languages, including JavaScript, C++, and more.",
                            Name = "Haxe",
                            Tags = new[] { "Haxe", "High-Level", "Cross-Compilation" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("0bbd66ce-c508-4838-8b48-bbf1aadf3d4d"),
                            Description = "Io is a small, prototype-based programming language inspired by Smalltalk, Lisp, and other languages.",
                            Name = "Io",
                            Tags = new[] { "Io", "Prototype-Based", "Small" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("1ec27d72-fb37-484a-8c44-8a0ea05e3fe7"),
                            Description = "J is a high-level, interpreted programming language, primarily used for mathematical and statistical analysis.",
                            Name = "J",
                            Tags = new[] { "J", "Mathematical", "Interpreted" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("213b5b57-bca5-4091-994a-6edcaf280b0f"),
                            Description = "Maxima is a computer algebra system based on a 1982 version of Macsyma.",
                            Name = "Maxima",
                            Tags = new[] { "Maxima", "Algebra", "Mathematics" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("b27c0c34-3861-4c6a-b9d1-ab4520a58999"),
                            Description = "ML is a general-purpose functional programming language developed by Robin Milner and others in the early 1970s.",
                            Name = "ML",
                            Tags = new[] { "ML", "Functional", "General Purpose" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("717af208-2d1c-4f6f-86cb-d9a4aa4154d3"),
                            Description = "Nim is a statically typed, imperative programming language that focuses on performance, portability, and expressiveness.",
                            Name = "Nim",
                            Tags = new[] { "Nim", "Statically Typed", "Performance" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("faf99fff-dec4-41c8-9ac1-5105790bed33"),
                            Description = "Objective-C is a general-purpose, object-oriented programming language used by Apple for the macOS and iOS operating systems.",
                            Name = "Objective-C",
                            Tags = new[] { "Objective-C", "Object-Oriented", "Apple" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("62e1cb39-4d48-4a1a-86de-a5fb5baacdcd"),
                            Description = "OCaml is a general-purpose, functional, and imperative programming language.",
                            Name = "OCaml",
                            Tags = new[] { "OCaml", "Functional", "General Purpose" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("dd91faaa-2ae7-4776-bca3-45842f4ccb30"),
                            Description = "Pascal is an influential imperative and procedural programming language, designed in the late 1960s as a small and efficient language intended to encourage good programming practices.",
                            Name = "Pascal",
                            Tags = new[] { "Pascal", "Imperative", "Efficient" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("b3bb13e5-4616-46bc-a624-aae37071b9f6"),
                            Description = "PL/I is a procedural, imperative computer programming language designed for scientific, engineering, business, and systems programming applications.",
                            Name = "PL/I",
                            Tags = new[] { "PL/I", "Procedural", "Scientific" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("18166ef0-d704-49c3-b870-106a2265499d"),
                            Description = "PostScript is a page description language and programming language used primarily in the electronic and desktop publishing areas.",
                            Name = "PostScript",
                            Tags = new[] { "PostScript", "Page Description", "Publishing" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("3d03005b-7eea-4718-8cab-3aceff35c122"),
                            Description = "PowerShell is a task automation and configuration management framework from Microsoft, consisting of a command-line shell and associated scripting language.",
                            Name = "PowerShell",
                            Tags = new[] { "PowerShell", "Automation", "Microsoft" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("d036b935-6c3d-44e7-bf35-95fe59ebfd4c"),
                            Description = "PureScript is a strongly-typed functional programming language that compiles to JavaScript.",
                            Name = "PureScript",
                            Tags = new[] { "PureScript", "Functional", "TypeScript" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("919c3d95-4895-4c75-b3d4-7e5186e5c874"),
                            Description = "REXX is an interpreted language that is used primarily for text processing.",
                            Name = "REXX",
                            Tags = new[] { "REXX", "Interpreted", "Text Processing" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("460ee986-c4cf-435a-9668-31547928f06d"),
                            Description = "Ring is a dynamic and general-purpose programming language that is designed to be simple and easy to learn.",
                            Name = "Ring",
                            Tags = new[] { "Ring", "General Purpose", "Dynamic" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("6b7ca78b-562b-4841-a081-327f67573791"),
                            Description = "SAS is a software suite used for advanced analytics, business intelligence, and data management.",
                            Name = "SAS",
                            Tags = new[] { "SAS", "Analytics", "Data Management" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("37770c83-a48a-4cc6-b35e-2885460ccad6"),
                            Description = "Scratch is a visual programming language and online community where users can create their own interactive stories, games, and animations.",
                            Name = "Scratch",
                            Tags = new[] { "Scratch", "Visual", "Education" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("5f8eb85f-87b1-4435-bff4-57da097f337c"),
                            Description = "Tcl is a high-level, dynamic programming language often used for rapid prototyping and scripting.",
                            Name = "Tcl",
                            Tags = new[] { "Tcl", "Scripting", "Dynamic" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("0c3cc21a-a4fb-48ef-96d9-9358da8cf4ba"),
                            Description = "Turing is a Pascal-like programming language developed for teaching programming concepts to beginners.",
                            Name = "Turing",
                            Tags = new[] { "Turing", "Education", "Teaching" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("aa4480c9-23f0-4400-9405-52f3ee67f9cd"),
                            Description = "Vim script is a scripting language used for customizing and extending the Vim text editor.",
                            Name = "Vim script",
                            Tags = new[] { "Vim", "Scripting", "Text Editor" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("66318db4-34fb-41e2-8fa3-ae754adf421b"),
                            Description = "Visual Basic is a third-generation event-driven programming language from Microsoft.",
                            Name = "Visual Basic",
                            Tags = new[] { "Visual Basic", "Microsoft", "Event-Driven" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("7a788c3a-1bda-40b5-a837-9c91b65d8374"),
                            Description = "X10 is a high-level programming language that is designed for high-performance, high-productivity computing.",
                            Name = "X10",
                            Tags = new[] { "X10", "High-Performance", "Concurrent" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("fd36a019-d08f-49c1-8bcf-787f21b1d33f"),
                            Description = "Zig is a general-purpose programming language designed for robustness, optimality, and maintainability.",
                            Name = "Zig",
                            Tags = new[] { "Zig", "General Purpose", "Robust" },
                            Type = "Programming Language"
                        },
                        new
                        {
                            Id = new Guid("88ca9776-8499-4c72-a145-d0821c2e125d"),
                            Description = "Visual Studio Code is a free source-code editor made by Microsoft for Windows, Linux, and macOS.",
                            Name = "Visual Studio Code",
                            Tags = new[] { "IDE", "Editor", "Microsoft" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("f5dbffe9-c339-4fbc-8c38-79288712d068"),
                            Description = "IntelliJ IDEA is a powerful Java integrated development environment (IDE) for developing computer software.",
                            Name = "IntelliJ IDEA",
                            Tags = new[] { "IDE", "Java", "JetBrains" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("0ac72bff-39b1-49fd-9d50-91535e7f8a90"),
                            Description = "Eclipse is an integrated development environment (IDE) used in computer programming.",
                            Name = "Eclipse",
                            Tags = new[] { "IDE", "Java", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("c94c54d0-6593-4732-b3a7-7ceb68abd571"),
                            Description = "PyCharm is an integrated development environment (IDE) used in computer programming for Python language.",
                            Name = "PyCharm",
                            Tags = new[] { "IDE", "Python", "JetBrains" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("f4718d55-65e7-4ab0-8403-8088d6cb3f78"),
                            Description = "Sublime Text is a proprietary cross-platform source code editor with a Python application programming interface (API).",
                            Name = "Sublime Text",
                            Tags = new[] { "Editor", "Text Editor", "Proprietary" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("8d0c1191-b011-4632-8b82-5fb23466aa61"),
                            Description = "Atom is a free and open-source text and source code editor for macOS, Linux, and Microsoft Windows.",
                            Name = "Atom",
                            Tags = new[] { "Editor", "Text Editor", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("ea4719cc-9d0c-42d1-80aa-0b1e8a39a65f"),
                            Description = "Visual Studio is an integrated development environment (IDE) developed by Microsoft.",
                            Name = "Visual Studio",
                            Tags = new[] { "IDE", "Microsoft", "Windows" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("1bc896ae-3572-4e56-856c-898e18c98de0"),
                            Description = "NetBeans is an integrated development environment (IDE) for Java. It supports development of all Java application types.",
                            Name = "NetBeans",
                            Tags = new[] { "IDE", "Java", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("7983c7e0-c461-4cb7-92a8-feb3a7f012ae"),
                            Description = "Xcode is an integrated development environment (IDE) for macOS containing a suite of software development tools.",
                            Name = "Xcode",
                            Tags = new[] { "IDE", "Apple", "macOS" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("816bbcc3-c267-4bc6-b038-d82a90e81b15"),
                            Description = "Android Studio is the official integrated development environment (IDE) for Android application development.",
                            Name = "Android Studio",
                            Tags = new[] { "IDE", "Android", "Google" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("dec7c8fe-8554-43f8-935e-4d226012a84f"),
                            Description = "Git is a distributed version control system for tracking changes in source code during software development.",
                            Name = "Git",
                            Tags = new[] { "Version Control", "Git", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("c2cf4df5-d730-4289-9bf9-d507cda553fd"),
                            Description = "GitHub is a web-based platform for version control and collaboration using Git.",
                            Name = "GitHub",
                            Tags = new[] { "Version Control", "Collaboration", "Web" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("4edd5828-0520-4b40-8f0f-8ae06d9f229d"),
                            Description = "Jupyter Notebook is an open-source web application that allows you to create and share documents that contain live code, equations, visualizations, and narrative text.",
                            Name = "Jupyter Notebook",
                            Tags = new[] { "Notebook", "Python", "Data Science" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("0f0ca3f1-5486-40d1-a0de-3bc6cd4daa46"),
                            Description = "Docker is a set of platform as a service (PaaS) products that use OS-level virtualization to deliver software in packages called containers.",
                            Name = "Docker",
                            Tags = new[] { "Containerization", "Virtualization", "DevOps" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("b6e6bc48-03e8-4f49-a906-39222690b56f"),
                            Description = "Postman is a collaboration platform for API development that simplifies the process of developing APIs that allow software to communicate.",
                            Name = "Postman",
                            Tags = new[] { "API Development", "Testing", "Collaboration" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("44b74011-2510-43c3-89b3-9036612de069"),
                            Description = "Webpack is an open-source JavaScript module bundler. It takes modules with dependencies and generates static assets representing those modules.",
                            Name = "Webpack",
                            Tags = new[] { "Module Bundler", "JavaScript", "Build Tool" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("b11e1b53-8b5f-460b-9983-ee24565cf2b8"),
                            Description = "npm is a package manager for the JavaScript programming language.",
                            Name = "npm",
                            Tags = new[] { "Package Manager", "JavaScript", "Node.js" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("34c3ca73-8893-4e7b-a356-b2a8b3a4d507"),
                            Description = "Selenium is a portable framework for testing web applications. Selenium provides a playback tool for authoring functional tests.",
                            Name = "Selenium",
                            Tags = new[] { "Testing", "Web", "Automated Testing" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("8216c205-f057-4932-87ca-5b63b4221f59"),
                            Description = "Visual Studio Online is a web-based integrated development environment (IDE) for software developers.",
                            Name = "Visual Studio Online",
                            Tags = new[] { "IDE", "Microsoft", "Web" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("f24f60f0-abfd-4988-972d-d834fe27df8b"),
                            Description = "CMake is an open-source, cross-platform family of tools designed to build, test, and package software.",
                            Name = "CMake",
                            Tags = new[] { "Build Tool", "Cross-Platform", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("a723f82b-a268-44f2-a513-5998292b71d1"),
                            Description = "JIRA is a proprietary issue tracking product developed by Atlassian that allows bug tracking and agile project management.",
                            Name = "JIRA",
                            Tags = new[] { "Project Management", "Issue Tracking", "Atlassian" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("29f3f85f-555a-470d-9557-222d88dccbcb"),
                            Description = "Confluence is a web-based corporate wiki application developed by Atlassian.",
                            Name = "Confluence",
                            Tags = new[] { "Collaboration", "Wiki", "Atlassian" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("9b24ccf3-f183-4b67-ab9f-020cd9d60189"),
                            Description = "Slack is a proprietary business communication platform that offers many IRC-style features.",
                            Name = "Slack",
                            Tags = new[] { "Communication", "Collaboration", "Messaging" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("63fd3464-49a6-4e01-845b-5118c81dbfa2"),
                            Description = "Trello is a web-based list-making application originally made by Fog Creek Software in 2011, that was spun out to form the basis of a separate company in 2014.",
                            Name = "Trello",
                            Tags = new[] { "Project Management", "Agile", "Productivity" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("a1ac1845-746a-4e9f-8bbe-ff7f1b2c8920"),
                            Description = "Vagrant is an open-source software product for building and maintaining portable virtual software development environments.",
                            Name = "Vagrant",
                            Tags = new[] { "Virtualization", "Development Environment", "Open Source" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("1f7c908b-0a4c-4004-b0d2-b883c01b8ffc"),
                            Description = "Ansible is an open-source automation tool that automates software provisioning, configuration management, and application deployment.",
                            Name = "Ansible",
                            Tags = new[] { "Automation", "Configuration Management", "DevOps" },
                            Type = "Tool"
                        },
                        new
                        {
                            Id = new Guid("64871fdb-e608-4b2d-a5de-d9c24bd96759"),
                            Description = "Version control is a system that records changes to a file or set of files over time, so that you can recall specific versions later.",
                            Name = "Version Control",
                            Tags = new[] { "Version Control", "Collaboration", "History" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("b61706c4-83eb-4327-be98-8add296861fa"),
                            Description = "Agile is an iterative approach to software development that emphasizes flexibility, collaboration, and customer feedback.",
                            Name = "Agile",
                            Tags = new[] { "Agile", "Methodology", "Iterations" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("4c5f9315-a7a2-433b-8431-3551a044358f"),
                            Description = "DevOps is a set of practices that combines software development (Dev) and IT operations (Ops) to shorten the software development life cycle and improve deployment frequency.",
                            Name = "DevOps",
                            Tags = new[] { "DevOps", "Collaboration", "Automation" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("b6a3df7e-ff62-4fad-9636-3e84668374c0"),
                            Description = "An algorithm is a step-by-step procedure or formula for solving a problem or accomplishing a task.",
                            Name = "Algorithm",
                            Tags = new[] { "Algorithm", "Problem Solving", "Procedure" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("b2f0a003-d531-4167-9b31-82cf2dac1826"),
                            Description = "A data structure is a way of organizing and storing data in a computer so that it can be used efficiently.",
                            Name = "Data Structure",
                            Tags = new[] { "Data Structure", "Organization", "Efficiency" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("b8c1b778-77dd-4794-9eec-d4bb733532f7"),
                            Description = "An API (Application Programming Interface) is a set of rules and protocols that allows different software applications to communicate with each other.",
                            Name = "API",
                            Tags = new[] { "API", "Communication", "Integration" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("a08d4aab-9295-4f19-977d-78fd6cdec5f2"),
                            Description = "A database is an organized collection of structured information, or data, typically stored electronically in a computer system.",
                            Name = "Database",
                            Tags = new[] { "Database", "Data Storage", "Structured" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("2f6370dd-ca78-4a1a-a3e1-9e20f7926a62"),
                            Description = "Cloud computing is the delivery of computing services—servers, storage, databases, networking, software, over the Cloud (Internet).",
                            Name = "Cloud Computing",
                            Tags = new[] { "Cloud Computing", "Services", "Internet" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("fc629dfb-5712-45a6-8a36-3bf80ade509b"),
                            Description = "Machine learning is a subset of artificial intelligence that involves training computers to learn from data and improve their performance over time.",
                            Name = "Machine Learning",
                            Tags = new[] { "Machine Learning", "Artificial Intelligence", "Data" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("55714db2-1b23-4e11-9b19-eab9244a54b4"),
                            Description = "Artificial intelligence (AI) is the simulation of human intelligence in machines that are capable of performing tasks that typically require human intelligence.",
                            Name = "Artificial Intelligence",
                            Tags = new[] { "Artificial Intelligence", "Simulation", "Automation" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("1777a7ae-3a81-4ee2-85cc-ed5c34ed871e"),
                            Description = "Big data refers to extremely large datasets that may be analyzed computationally to reveal patterns, trends, and associations.",
                            Name = "Big Data",
                            Tags = new[] { "Big Data", "Data Analysis", "Patterns" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("1e08106f-b657-4cd6-89a8-49ff1fd727e0"),
                            Description = "Cybersecurity is the practice of protecting computer systems, networks, and data from theft, damage, or unauthorized access.",
                            Name = "Cybersecurity",
                            Tags = new[] { "Cybersecurity", "Protection", "Networks" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("41331c5c-f751-4f88-bda9-ddd1feb3cd5c"),
                            Description = "Code review is a systematic examination of computer source code. It is intended to find mistakes overlooked in initial development.",
                            Name = "Code Review",
                            Tags = new[] { "Code Review", "Quality Assurance", "Collaboration" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("ef6c441a-fd29-4b65-8ba9-159f68590a6f"),
                            Description = "Code refactoring is the process of restructuring existing computer code without changing its external behavior.",
                            Name = "Code Refactoring",
                            Tags = new[] { "Code Refactoring", "Code Improvement", "Restructuring" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("18d79a1b-d269-4730-97f4-31ebf0a9b253"),
                            Description = "Continuous Integration (CI) is a software development practice where code changes are automatically built, tested, and integrated into the shared repository.",
                            Name = "Continuous Integration",
                            Tags = new[] { "Continuous Integration", "Automation", "Testing" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("69a068bf-99ee-493f-9e00-1a04212521c4"),
                            Description = "Continuous Deployment is a software development practice where every code change that passes automated testing is automatically deployed to production.",
                            Name = "Continuous Deployment",
                            Tags = new[] { "Continuous Deployment", "Automation", "Production" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("f51a780b-2ac7-4d09-ad49-e5f252a5a628"),
                            Description = "Code quality refers to the overall robustness, maintainability, readability, and performance of a software codebase.",
                            Name = "Code Quality",
                            Tags = new[] { "Code Quality", "Robustness", "Maintainability" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("8c269479-ab22-41df-9b88-63c8593be02f"),
                            Description = "Unit testing is a software testing method where individual units or components of a software are tested in isolation.",
                            Name = "Unit Testing",
                            Tags = new[] { "Unit Testing", "Testing", "Components" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("d12de485-c52c-4f82-9f0e-ddad19ffde50"),
                            Description = "Continuous monitoring involves the regular collection and analysis of data to evaluate the performance and security of a system.",
                            Name = "Continuous Monitoring",
                            Tags = new[] { "Continuous Monitoring", "Performance", "Security" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("4ce6f220-29b7-4965-8506-7ffe7c9fcf7f"),
                            Description = "Responsive design is an approach to web design that makes web pages render well on a variety of devices and window or screen sizes.",
                            Name = "Responsive Design",
                            Tags = new[] { "Responsive Design", "Web", "User Experience" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("0e3635d2-b63a-4c87-b177-f82c97966e68"),
                            Description = "User Experience (UX) refers to a person's emotions and attitudes about using a particular product, system, or service.",
                            Name = "User Experience (UX)",
                            Tags = new[] { "User Experience", "Design", "Emotions" },
                            Type = "Concept"
                        },
                        new
                        {
                            Id = new Guid("8a81561e-6f84-4876-8f6c-b9831ab02f02"),
                            Description = "User Interface (UI) encompasses the visual elements, controls, and layouts through which a user interacts with a software or hardware.",
                            Name = "User Interface (UI)",
                            Tags = new[] { "User Interface", "Design", "Interactions" },
                            Type = "Concept"
                        });
                });

            modelBuilder.Entity("QuizQuizQuestion", b =>
                {
                    b.Property<Guid>("QuestionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuizzesId")
                        .HasColumnType("uuid");

                    b.HasKey("QuestionsId", "QuizzesId");

                    b.HasIndex("QuizzesId");

                    b.ToTable("QuizQuizQuestion", (string)null);
                });

            modelBuilder.Entity("TechInterestTechnology", b =>
                {
                    b.Property<Guid>("InterestedTechnologiesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TechInterestUserId")
                        .HasColumnType("uuid");

                    b.HasKey("InterestedTechnologiesId", "TechInterestUserId");

                    b.HasIndex("TechInterestUserId");

                    b.ToTable("TechInterestTechnology");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.QuestionOption", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.QuizQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwiz.Api.Entities.SubmissionSelection", "SubmissionSelection")
                        .WithMany("SelectedOptions")
                        .HasForeignKey("SubmissionSelectionId");

                    b.Navigation("Question");

                    b.Navigation("SubmissionSelection");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Submission", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.Quiz", "Quiz")
                        .WithMany("Submissions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.SubmissionSelection", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.QuizQuestion", "Question")
                        .WithMany("SubmissionSelections")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwiz.Api.Entities.Submission", null)
                        .WithMany("Selections")
                        .HasForeignKey("SubmissionId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("QuizQuizQuestion", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.QuizQuestion", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwiz.Api.Entities.Quiz", null)
                        .WithMany()
                        .HasForeignKey("QuizzesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TechInterestTechnology", b =>
                {
                    b.HasOne("Kwiz.Api.Entities.Technology", null)
                        .WithMany()
                        .HasForeignKey("InterestedTechnologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kwiz.Api.Entities.TechInterest", null)
                        .WithMany()
                        .HasForeignKey("TechInterestUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Quiz", b =>
                {
                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.QuizQuestion", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("SubmissionSelections");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.Submission", b =>
                {
                    b.Navigation("Selections");
                });

            modelBuilder.Entity("Kwiz.Api.Entities.SubmissionSelection", b =>
                {
                    b.Navigation("SelectedOptions");
                });
#pragma warning restore 612, 618
        }
    }
}
